version"3"
services:
  tachidesk:
    image: ghcr.io/suwayomi/tachidesk
    container_name: tachidesk
    environment:
      - PUID=0
      - PGID=0 #群晖为1026、100，其他为1000、1000
      - TZ=Asia/Shanghai
    volumes:
      - /com:/root/.local/share/Tachidesk  #将“本地路径”替换为在设备建立的文件夹路径
    ports:
      - "127.0.0.1:3001:4567" #按需更改端口
    restart: always
